import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-privacy-policy',
  templateUrl: './privacy-policy.component.html',
  styleUrls: ['./privacy-policy.component.scss']
})
export class PrivacyPolicyComponent implements OnInit {

  readonly content = `
  <h1>Privacy Policy</h1>
<p>This website privacy policy (&ldquo;Privacy Policy&rdquo; or &ldquo;Policy&rdquo;) describe&nbsp; &nbsp;(herein after referred to as &ldquo; OBOX&rdquo;, &ldquo;Site&rdquo; or &ldquo;Website&rdquo;) policy on the collection, use, and disclosure of information about you in connection with your use of the domain,&nbsp; &nbsp;and all associated product sites listed on our Site. The terms&nbsp;&ldquo;we&rdquo;,&nbsp;&ldquo;us&rdquo; or&nbsp;&ldquo;our&rdquo;, refer to&nbsp; . When you use the service available at our Website, you consent to our collection, use, and disclosure of information about you as described in this Privacy Policy. The Site is owned and controlled by Click Labs Inc, Click Labs Inc, 4830 West Kennedy Blvd, Suite 600, Tampa, Florida, 33609 United States of America.</p>
<p>We reserve the right to update, change, amend or modify this Privacy Policy at any time and said changes will be effective upon posting. Every time there is a change, we will display a notice on our Site thereof. We shall also notify you by email. We will use your personal information in a manner consistent with the Privacy Policy in effect at the time you submitted the information unless you consent to the new or revised policy. This Privacy Policy also applies to software products listed on the Site, namely Yelo, Tookan, Kato, Fugu, Hippo, Bulbul, Flight Map and Tida.</p>
<p>In every respect, by using the Site, you agree to be bound by terms of this Privacy Policy.</p>
<h2>1. Introduction</h2>
<p>1.1 Your privacy is important to you and to us, so we'll protect the information you share with us. To protect your privacy, the Site&nbsp;follows different principles in accordance with worldwide practices for customer privacy and data protection.</p>
<p>1.2 We at  OBOX are committed to respecting your online privacy and recognize your need for appropriate protection and management of any personally identifiable information (&ldquo;Personal Information&rdquo;) you share with us. For purpose of this Policy, Personal Information means any information that may be used to identify an individual, including, but not limited to, a first and last name, a home or other physical address and an email address or other contact information, whether at work or at home. In general, you can visit the Site's web pages without telling us who you are or revealing any Personal Information about yourself. If, however, Personal Information is reveled to us, we won't sell or give away any content of your Personal Information to anyone and use state-of-the-art security measures to protect your information from unauthorized users.</p>
<p>1.3 For customers in Europe - if and when we collect or use your personal information, we shall do so within the framework of General Data Protection Regulation (GDPR) (Regulation (EU) 2016/679) and any related legislation, regulations, requirements or guidance from time to time for us to comply. For purpose of clarity, &lsquo;Personal Data' shall have the meaning given to it in the General Data Protection Regulation (GDPR) (Regulation (EU) 2016/679).</p>
<h2>2. Information we collect and how we use it</h2>
<p>2.1 When you visit or use our service, we collect and store information about you, your computer or mobile device and your activities. This information may include, but is not limited to:</p>
<p>2.2.1 your computer's IP address; technical information about your computer or mobile device (such as type of device, web browser or operating system);</p>
<p>2.2.2 your mobile device's unique ID number (when available), your mobile device's geographic location (specific geographic location if you've enabled collection of that information, or general geographic location automatically);</p>
<p>2.2.3 your provided full name, email address, zip code and other information you may provide with your account, such as your gender and birth date;</p>
<p>2.2.4 how long you visited our service and which features you used;</p>
<p>2.2.5 you agree to comply with all applicable privacy and data protection regulations. Further, you agree to not use our service to send us sensitive information where unauthorized disclosure could cause material, severe, or catastrophic harm or impact to  OBOX, any data subjects or relying parties. Sensitive Information includes, passwords, authentication/authorization credentials, information under strict regulatory or contractual handling requirements (e.g., PCI, HIPAA, and state and federal data security laws) such as, credit card information, credit card numbers, CIV numbers (three digit codes for Visa and MasterCard, four digit code for American Express) and magnetic stripe information, social security numbers, driver's license numbers, passport numbers, government issued identification numbers, financial account information, health data, biometric data, personally identifiable information knowingly collected from children under the age of 13 or from online services directed toward children, real time geolocation data which can identify an individual, business secrets deemed highly confidential (e.g., highly-confidential business strategies and communications, sensitive attorney-client privileged and confidential communications). We collect, store, and use your user data on our servers to provide you with the ability to better maintain and improve your services. We may also use data in an aggregated form for our own purposes. Our services transfer data to servers that store user data in the United States of America (&ldquo;USA&rdquo;) and outside USA.</p>
<p>2.3 Additionally, we shall not be liable for any loss or damage sustained by reason of any disclosure (inadvertent or otherwise) of any information concerning the user's account and / or information relating to or regarding online transactions using credit cards / debit cards and / or their verification process and particulars nor for any error, omission or inaccuracy with respect to any information so disclosed and used whether or not in pursuance of a legal process or otherwise.</p>
<p>2.4 We use the information to improve the Service's functionality, quality and also personalize your experience. We also use this information to display relevant advertising, provide support, message you, and comply with legal obligations.</p>
<p>2.5 Please note that some of this information is automatically collected without you voluntarily choosing to provide this information to us.</p>
<h2>3. Notice</h2>
<p>We will ask you when we need information that personally identifies you or allows us to contact you. Generally, this information is requested when you create a registration or login ID on the Site or when you connect or browse connected sites, linked or listed on our Website, or join a limited-access premium site. We use your Personal Information for four primary purposes:</p>
<p>a. to make the site easier for you to use by not having to enter information more than once;</p>
<p>b. to help you quickly find services or information that you are looking for;</p>
<p>c. to help us create content most relevant to you;</p>
<p>d. to alert you to special offers, updated information and other new services available on our Site.</p>
<h2>4. Third Party Services</h2>
<p>Our services are designed to allow you to assign tasks to field workers, communicate with your field workers and customers (&ldquo;Users&rdquo;), and view information pertaining to your field workers' activity.  OBOX does this in part using GPS and other sensors on devices running our software products and applications. Some information is automatically collected from or about your Users and field workers when you use our services and may include, for example, geographic coordinates, phone numbers, names, and addresses.</p>
<h2>5. Consent</h2>
<p>5.1 If you choose not to register or provide Personal Information, you can still use most of the Website. But you will not be able to access areas that require registration. If you decide to register, you will be able to select the kinds of information you want to receive from us by subscribing to various services, like our electronic newsletters. If you do not want us to communicate with you about other offers regarding the Site's programs, events, or Services by email, postal mail, or telephone, you may select the option stating that you do not wish to receive messages from us.</p>
<p>5.2 By accessing our Site you agree to allow us to share data lawfully, with third parties who work on our behalf to provide your services, to comply with laws or to respond to lawful requests and legal process (provided that  OBOX will endeavor to notify you if  OBOX has received a lawful request for your information), to protect the rights and property of  OBOX, our agents, customers, and others including to enforce our agreements, policies, and terms of use, in an emergency, including to protect the personal safety of any person; and for the purposes of a business deal (or negotiation of a business deal) involving sale or transfer of all or a part of our business or assets (business deals may include, for example, any merger, financing, acquisition, divestiture, or bankruptcy transaction or proceeding).</p>
<h2>6. Access</h2>
<p>We will provide you with the means to ensure that your Personal Information is correct and current. You may review and update this information at any time at the login section. There, you can:</p>
<p>a. view and edit personal information you have already given us;</p>
<p>b. tell us whether you want us to send you marketing information, or whether you want third parties to send you their offers by postal mail;</p>
<p>c. sign up for electronic newsletters about our services and products; and</p>
<p>d. Register. Once you register, you won't need to do it again. Wherever you go on the Site, your information stays with you.</p>
<h2>7. Security</h2>
<p>7.1 The Site has taken strong measures to protect the security of your Personal Information and to ensure that your choices for its intended use are honored. We take strong precautions to protect your data from loss, misuse, unauthorized access or disclosure, alteration, or destruction.</p>
<p>7.2 You also have a significant role in protecting your information. No one can see or edit your Personal Information without knowing your user name and password, so do not share these with others.</p>
<p>7.3 Data Security: In addition to the above,  OBOX will maintain security procedures and practices to store in a secure fashion and protect all personally identifiable information regarding the end user (&ldquo;PII&rdquo;) that is collected by  OBOX and stored in a database owned or controlled by  OBOX (the &ldquo;Database&rdquo;), against accidental or unlawful destruction or loss, unauthorized disclosure or access. Such security procedures and practices shall be implemented in accordance with all applicable data protection laws and shall be appropriate to the nature of the information collected and shall be aligned with industry standard practices for the management, transport, and storage of PII.</p>
<h2>8. Notice To Parents</h2>
<p>8.1 We want to help you guard your children's privacy. We encourage you to talk to your children (below 13 years) about safe and responsible use of their Personal Information while using our Site. The Site does not publish content that is harmful, derogatory or pornographic in nature. However, the Website shall not incur any liability should your children provide us any Personal Information without parental consent. If you become aware that a child has provided us with personal information without parental consent, please contact us at&nbsp;<a href="mailto:contact@ OBOX.com">contact@ OBOX.com</a>. If we become aware that a child under 13 has provided us with Personal Information without parental consent, we take steps to remove such information and terminate the child's account.</p>
<h2>9. Registration</h2>
<p>9.1 When you login to the Site's secure pages, we may ask you to register yourself electronically. When you do, we merge your registration information with any information you've already left with us (we call that information your personal profile). If you haven't previously registered with us, we create a personal profile for you from your registration information. If you ever want to review or update that information, you can visit the Site, click on update profile, and edit any of the Personal Information in your profile.</p>
<h2>10. Customer Profiles</h2>
<p>10.1 As mentioned above, every registered customer has a unique personal profile. Each profile is assigned a unique personal identification number, which helps us ensure that only you can access your profile.</p>
<p>10.2 Cookies:&nbsp;When you visit our Site, we may place &ldquo;cookies&rdquo; on your computer to recognize you. We do this to store your preferences, collect statistical data and track your use of our service. Cookies are widely used, and most web browsers are configured initially to accept cookies automatically. If you prefer not to accept cookies, you may adjust and configure your browser settings accordingly. However, if you turn off cookies, or refuse to accept a request to place a cookie, some features and services on the Site may not function properly. Ad companies (including but not limited to Google and Facebook) may also place cookies on your computer to track your activities across various sites so that they can display targeted advertisements. In addition to above you are requested to read our cookie policy at&nbsp;<a href="https:// OBOX.com/privacy-policy/">https:// OBOX.com/privacy-policy/</a></p>
<p>10.3 We provide you with access to your user data and ability to delete any of your user data. We also take commercially reasonable steps to safeguard user data. We may also collect registration and other information about you as our customer through our Site. Our collection and use of information collected about you on our website is governed by this Privacy Policy.</p>
<h2>11. What we do with the information you share</h2>
<p>11.1 When you join us, you provide us with your contact information, including your name and email address. We use this information to send you updates about our services, questionnaires to measure your satisfaction with our service and announcements about new and exciting services that we offer.</p>
<p>11.2 We will disclose your Personal Information, without notice, only if required to do so by law or in the good faith belief that such action is necessary to: (a) confirm to the edicts of the law or comply with legal process served on the Site; (b) protect and defend the rights or property of Jungle works; and (c) act in urgent circumstances to protect the personal safety of users of Jungle works or the public.</p>
<h2>12. Information sharing and disclosure</h2>
<p>12.1 We do not rent or sell Personal Information about you with other people (save with your consent) or non-affiliated companies, except to provide services you&rsquo;ve requested, under the following circumstances:</p>
<p>a. We respond to court orders, legal proceedings or to establish or exercise our legal rights or defend against legal claims.</p>
<p>b. We believe it is necessary to share information in order to investigate, prevent, or take action regarding illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, violations of the Website&rsquo;s terms of use, or as otherwise required by law.</p>
<p>c. We shall transfer information about you only if we are acquired by another company or individual. In this event, the Website will notify you before information about you is transferred and becomes subject to a different privacy policy.</p>
<p>d. We may need to contact you to comply or co-operate with a legal request. For this purpose, we will use the email address provided to us by you. All communications sent by us at such email address shall be deemed to have been communicated to you.</p>
<h2>13. Confidentiality and security</h2>
<p>13.1 We limit access to Personal Information about you to employees who we believe reasonably need to come into contact with that information to provide products or services to you or in order to do their jobs.</p>
<p>13.2 We have physical, electronic, and procedural safeguards that comply with the laws prevalent in the United States of America (USA) and elsewhere we provide our services to protect personal information about you. We seek to ensure compliance with applicable technology laws to ensure the protection and preservation of your privacy. Additionally, we follow generally accepted industry standards to protect the Personal Information submitted to us, both during transmission and once we receive it. However, no method of transmission over the Internet or via mobile device, or method of electronic storage, is 100% secure. Therefore, while we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.</p>
<h2>14. Your Consent</h2>
<p>14.1 By using the Website, you consent to the terms of our Privacy Policy and to the Site&rsquo;s processing of Personal Information for the purposes given above as well as those explained where we at&nbsp;<a href="https:// OBOX.com/">https:// OBOX.com</a>collect personal information on the web.</p>
<h2>15. Contact Information</h2>
<p>15.1 We welcome your comments regarding this privacy statement at the contact address given at the website. Should there be any concerns about contravention of this Privacy Policy, we will employ all commercially reasonable efforts to address the same. The terms in this Policy may be changed by us at any time.  OBOX is free to offer its services to any client/prospective client without restriction.</p>
  `;
  constructor() { }

  ngOnInit() {
  }

}
